export const SET_COLUMNID = 'SET_COLUMNID'
export const SET_TAGID = 'SET_TAGID'
export const SET_HOTPEOPLE = 'SET_HOTPEOPLE'
export const SET_ARTICLES = 'SET_ARTICLES'
export const SET_HOTTAGS = 'SET_HOTTAGS'
